export default {
    SAVE_USER: "SAVE_USER_ACTION",
    SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
    SAVE_USER_PENDING: "SAVE_USER_PENDING",
    LOGIN_USER: "LOGIN_USER_ACTION",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_PENDING: "LOGIN_USER_PENDING",
    DISABLE_REDIRECT: "DISABLE_REDIRECT",
    STOP_SESSION: "STOP_SESSION"
};